#!/bin/bash
inst_hook pre-mount 10 "$moddir"/olpc-boot-premount.sh
inst_hook pre-pivot 10 "$moddir"/olpc-boot-prepivot.sh

dracut_install dd
dracut_install rm
dracut_install mv
dracut_install ln
dracut_install sync
dracut_install sleep
dracut_install poweroff
dracut_install umount

for i in activate.py upfs.py olpc_act_gui_server.py; do
	inst "$moddir"/"$i" /usr/libexec/initramfs-olpc/"$i"
done

for i in cprl.so pyvt.so pyfb.so ipv6util.so olpc_act_gui_client.py; do
	inst "$moddir"/"$i" /usr/lib/python2.6/site-packages/"$i"
done

for i in "$moddir"/act-gui-images/*; do
	inst "$i" /usr/share/olpc-act-gui/images/$(basename "$i")
done

old_ifs=$IFS
IFS="
"
for line in $(<"$moddir"/python-contents.txt); do
	inst $line
done
IFS=$old_ifs
