#!/bin/bash

# cmdline hook must be installed to run after 10parse-root-opts but before
# 95parse-block
inst_hook cmdline 20 "$moddir"/olpc-boot-cmdline.sh

inst_hook pre-mount 10 "$moddir"/olpc-boot-premount.sh
inst_hook pre-pivot 10 "$moddir"/olpc-boot-prepivot.sh

dracut_install dd
dracut_install rm
dracut_install mv
dracut_install ln
dracut_install sync
dracut_install sleep
dracut_install poweroff
dracut_install umount
dracut_install readlink
dracut_install dirname
dracut_install basename
dracut_install mktemp

# mount points used by initramfs code
mkdir -p "$initdir"/ofw
mkdir -p "$initdir"/mnt/usb
mkdir -p "$initdir"/mnt/sd

inst /usr/lib/dracut-modules-olpc/cprl /usr/libexec/initramfs-olpc/cprl


